### ISSUE TITLE
show error description

### ISSUE THREAD

**Issue by punund** [wmira/dropkit#2]
Upon unsuccessful return (such as status 4xx) I just get the status, however, response body contains valuable explanation, which I would like to see.  Maybe this `if` is not needed:

https://github.com/wmira/dropkit/blob/master/index.js#L21

**Comment by wmira** [comment]
I have updated this and change parameter on rejection. e.g.

``` javascript
 v2.accounts().then(function(account) {
    console.log(account);
 }).error(function(error) {
    console.log("httpStatusCode: " + error.statusCode);
    console.log("response: " + error.res);
 });
```

**Comment by punund** [comment]
:+1:
